# Generated by Django 3.0.1 on 2020-07-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
