# Generated by Django 3.0.1 on 2020-07-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
