# Generated by Django 3.0.1 on 2020-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator',
            field=models.CharField(blank=True, default='user', max_length=50, null=True),
        ),
    ]
