# Generated by Django 3.0.1 on 2020-07-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200709_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categori',
            field=models.CharField(choices=[('test', 'Test'), ('hello', 'Hello')], default='test', max_length=50),
        ),
    ]
