# Generated by Django 3.0.1 on 2020-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_categori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categori',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('test', 'Test'), ('hello', 'Hello')], default='test', max_length=50),
        ),
    ]
