# Generated by Django 3.0.1 on 2020-07-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200709_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('test', 'Test'), ('hello', 'Hello')], default='test', max_length=50, null=True),
        ),
    ]
