# Generated by Django 3.0.1 on 2020-07-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200711_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
