# Generated by Django 3.0.1 on 2020-07-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Consumer Goods', 'Consumer Goods'), ('Household Appliances', 'Houshold Appliances'), ('Food and Beverage', 'Food and Beverage'), ('Automobiles', 'Automobiles'), ('Musical Instruments', 'Musical Instruments'), ('Sporting Goods', 'Sporting Goods'), ('Other', 'Other')], default='test', max_length=50, null=True),
        ),
    ]
