# Generated by Django 3.0.1 on 2020-07-21 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_follows', to=settings.AUTH_USER_MODEL)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
